services:
  db:
    image: postgres:17
    container_name: purple_api_demo
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_demo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
