import type { Metadata } from 'next';
import { Footer, Header, ProgressBar } from '@/layout';
import { dmSans } from '@/fonts';
import '@/styles/globals.css';
import { Toasts } from '@/components';
import { PropsWithChildren } from 'react';
import { CartProvider } from '@/context/cartContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface Props extends PropsWithChildren<JSX.Element> {}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ru">
      <body className={dmSans.className}>
        <div className="wrapper">
          <ProgressBar />
          <CartProvider>
            <Header />
            <main className="main">{children}</main>
            <Footer />
            <Toasts />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
