import type { Metadata } from 'next';
import { Footer, Header, ProgressBar } from '@/layout';
import { dmSans } from '@/fonts';
import '@/styles/globals.css';
import { Toasts } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={dmSans.className}>
        <div className="wrapper">
          <ProgressBar />
          <Header />
          <main>{children}</main>
          <Footer />
          <Toasts />
        </div>
      </body>
    </html>
  );
}
